### PR TITLE
DEV: Update dependencies and maintainers

### PR DESCRIPTION
**Pull request by shaneahmed**
- Update dependencies and maintainers.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by shaneahmed** [comment]
@conda-forge-admin, please rerender

**Comment by sarthakpati** [comment]
Seems like the failure is because `wsidicom` is not present in the conda channels. I just added the recipe for review: https://github.com/conda-forge/staged-recipes/pull/18878

**Comment by sarthakpati** [comment]
Merged, and it should be available in conda channels in ~1-2 hours: https://github.com/conda-forge/wsidicom-feedstock

**Review by sarthakpati — APPROVED** [review]
LGTM!

**Comment by sarthakpati** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
