### PR TITLE
:pushpin: Pin dependencies for the new release

### PR DESCRIPTION
**Pull request by shaneahmed**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by shaneahmed** [comment]
@conda-forge-admin, please rerender

**Comment by shaneahmed** [comment]
The build fails for Python 3.12. I have specified Python version to be `python >=3.8, <=3.11` but it still fails, any ideas?
@sarthakpati

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=845067&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=189

**Comment by sarthakpati** [comment]
Can you check if #19 fixes this?

**Comment by shaneahmed** [comment]
> Can you check if #19 fixes this?

I have updated the dependencies in #19

**Comment by shaneahmed** [comment]
Fixed in #19

**Pull request closed without merging**
